# Generated by Django 4.2.1 on 2023-06-12 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(choices=[('KNE', 'KNE'), ('KLF', 'KLF'), ('Farm Star', 'Farm Star'), ('Sameer', 'Sameer')], default='Sameer', max_length=255)),
                ('mood', models.CharField(blank=True, max_length=255, null=True)),
                ('mood_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
